name: CI-macOS

on:
  push:
    branches: [master, develop]

jobs:
  build-and-test:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_12.4.app
    - name: Xcode version
      run: /usr/bin/xcodebuild -version
    - name: Build and Test
      run: xcodebuild clean build test -project SeLoger/SeLoger.xcodeproj -scheme "CI_macOS" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -sdk macosx -destination "platform=macOS" ONLY_ACTIVE_ARCH=YES SWIFT_TREAT_WARNINGS_AS_ERRORS=YES
